# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add User Flow Reports

on:
  pull_request:
  push:
    branches: [master]

jobs:
  collect_user_flows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Collect user flows
        run: npm run analyze:user-flows

      - name: Commit measures
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Persist user flow reports'
          add: '*'
