# This file executes @push-based/user-flow against the served SSR version of the current PR
name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Executing user-flow CLI
        uses: push-based/user-flow-gh-action@v0.0.0-alpha.20
        with:
          rcPath: ./projects/movies-user-flows/.user-flowrc.json
